# Streamlit secrets configuration for Google Cloud Vision API
# Copy your service-account-key.json content into this format for Streamlit Cloud deployment

[gcp_service_account]
type = "service_account"
project_id = "your-project-id"
private_key_id = "your-private-key-id" 
private_key = "-----BEGIN PRIVATE KEY-----\nYour private key content here\n-----END PRIVATE KEY-----\n"
client_email = "your-service-account@your-project.iam.gserviceaccount.com"
client_id = "your-client-id"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/your-service-account%40your-project.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

# INSTRUCTIONS FOR STREAMLIT CLOUD:
# 1. Go to your app settings on Streamlit Cloud
# 2. Click on "Secrets" in the left sidebar
# 3. Copy and paste the above configuration with your actual values from service-account-key.json
# 4. Make sure to escape the private key properly (replace newlines with \n)
# 5. Save the secrets configuration
# 6. Restart your Streamlit app
