# Streamlit secrets configuration
# This file shows the structure - you'll need to add your actual Google Cloud credentials in Streamlit Cloud

[gcp_service_account]
# You'll paste your service-account-key.json content here when deploying to Streamlit Cloud
